FROM nvidia/cuda:10.0-base-ubuntu18.04

ENV LANG=C.UTF-8

RUN apt-get update -y && apt-get install -y \
    git \
    wget \
    curl \
    cmake \
    unzip \
    software-properties-common \
    unixodbc-dev \
    gcc \
    g++

RUN : \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common \
    && add-apt-repository -y ppa:deadsnakes \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        python3.8-venv \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && :

RUN python3.8 -m venv /venv
ENV PATH=/venv/bin:$PATH

RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113

RUN pip install numpy \
    pandas \
    transformers~=4.18.0 \
    tensorboard \
    seqeval \
    datasets \
    protobuf~=3.19.0 \
    sentencepiece

COPY ../MultiwordExpressions /home/MultiwordExpressions
WORKDIR /home/MultiwordExpressions/
RUN cd /home/MultiwordExpressions/

ENTRYPOINT ["python","-m", "examples.mwe.en.run"]